# JMO Management System — Core Package
from app.core.scoring import (
    calculate_score,
    calculate_section_scores,
    ScoreResult,
    QuestionConfig,
    StudentAnswerData,
)
from app.core.ranking import compute_rankings, RankingInput, RankingResult
from app.core.attendance import (
    AttendanceRecord,
    SyncConflict,
    resolve_attendance_conflict,
    deduplicate_attendance,
)
from app.core.results import (
    calculate_assessment_result,
    validate_result_immutability,
    validate_paper_locked,
    validate_answer_key_locked,
    ResultCalculationInput,
    ResultCalculationOutput,
)
from app.core.permissions import (
    CurrentUser,
    BatchAssignment,
    is_admin,
    is_teacher,
    can_access_batch,
    can_access_student,
    can_publish_results,
    can_manage_users,
    can_manage_academic_structure,
    can_manage_papers_questions,
    can_enter_answers,
    can_upload_omr,
    can_review_omr,
    can_view_results,
    can_generate_reports,
    can_manage_awards,
    can_view_audit_logs,
    can_manage_custom_fields,
    can_manage_settings,
)

__all__ = [
    "calculate_score",
    "calculate_section_scores",
    "ScoreResult",
    "QuestionConfig",
    "StudentAnswerData",
    "compute_rankings",
    "RankingInput",
    "RankingResult",
    "AttendanceRecord",
    "SyncConflict",
    "resolve_attendance_conflict",
    "deduplicate_attendance",
    "calculate_assessment_result",
    "validate_result_immutability",
    "validate_paper_locked",
    "validate_answer_key_locked",
    "ResultCalculationInput",
    "ResultCalculationOutput",
    "CurrentUser",
    "BatchAssignment",
    "is_admin",
    "is_teacher",
    "can_access_batch",
    "can_access_student",
    "can_publish_results",
    "can_manage_users",
    "can_manage_academic_structure",
    "can_manage_papers_questions",
    "can_enter_answers",
    "can_upload_omr",
    "can_review_omr",
    "can_view_results",
    "can_generate_reports",
    "can_manage_awards",
    "can_view_audit_logs",
    "can_manage_custom_fields",
    "can_manage_settings",
]